const NavText = {
  en: {
    navHome: "Home",
    navBiography: "Biography",
    navPodcast: "Podcast",
    navMinistry: "Ministry",
    navEvents: "Events",
    navGallery: "Gallery",
    navContact: "Contact us",
    navPartner: "Partner with us",
  },
  fr: {
    navHome: "Accueil",
    navBiography: "Biographie",
    navPodcast: "Podcast",
    navMinistry: "Ministère",
    navEvents: "Événements",
    navGallery: "Galerie",
    navContact: "Contactez-nous",
    navPartner: "Partenaires",
  },
  es: {
    navHome: "Inicio",
    navBiography: "Biografía",
    navPodcast: "Podcast",
    navMinistry: "Ministerio",
    navEvents: "Eventos",
    navGallery: "Galería",
    navContact: "Contáctenos",
    navPartner: "Asóciese con nosotros",
  },
  pt: {
    navHome: "Início",
    navBiography: "Biografia",
    navPodcast: "Podcast",
    navMinistry: "Ministério",
    navEvents: "Eventos",
    navGallery: "Galeria",
    navContact: "Contato",
    navPartner: "Seja nosso parceiro",
  },
  ch: {
    navHome: "首页",
    navBiography: "传记",
    navPodcast: "播客",
    navMinistry: "事工",
    navEvents: "活动",
    navGallery: "画廊",
    navContact: "联系我们",
    navPartner: "与我们合作",
  },
};

export default NavText;
